driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: windows-2008r2-chef11.18.6
    driver_config:
      box: chef/windows-server-2008r2-standard
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: windows-2008r2-chef12
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2-chef11.18.6
    driver_config:
      box: chef/windows-server-2012r2-standard
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: windows-2012r2-chef12
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: client
    run_list:
      - recipe[sql_server::default]
    attributes: { sql_server: { accept_eula: true } }
  - name: server
    run_list:
      - recipe[sql_server::server]
    attributes: { sql_server: { accept_eula: true } }
