name             'sql_server'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache-2.0'
description      'Installs/Configures Microsoft SQL Server'
version          '5.6.0'
supports         'windows'
depends          'windows', '>= 3.0'
source_url       'https://github.com/chef-cookbooks/sql_server'
issues_url       'https://github.com/chef-cookbooks/sql_server/issues'
chef_version     '>= 13.0'
