name              'sql_server'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures Microsoft SQL Server'
version           '7.1.7'
source_url        'https://github.com/sous-chefs/sql_server'
issues_url        'https://github.com/sous-chefs/sql_server/issues'
chef_version      '>= 15.3'

supports          'windows'
